@startuml
(*) -down-> 数字A

数字A -down->[四則演算] 四則演算
数字A -down->[イコール / 数字A] 計算結果
数字A -->[数字 / 数字A] 数字A
数字B -left->[四則演算] 四則演算
数字B -right->[イコール / 計算結果] 計算結果
数字B --[hidden]>[イコール / 計算結果] 計算結果
数字B -->[数字 / 数字B] 数字B
四則演算 -right->[数字 / 数字B] 数字B
四則演算 --[hidden]>[数字 / 数字B] 数字B
四則演算 -down->[イコール / 計算結果] 計算結果
四則演算 -->[四則演算] 四則演算
計算結果 -up->[数字 / 数字A] 数字A
計算結果 -->[イコール] 計算結果
計算結果 -->[四則演算] 四則演算
}
@enduml