@startuml
start
floating note left: 状態が四則演算の場合の処理
 :BigDecimal a
 BigDecimal b
 string displayNum
 Operation ope|
if (数字押下) then (yes)
  :displayNum = 0に初期化;
  :displayNum = 押下された数字;
  :b = Integer.parseInt(displayNum);
  :displayNumを表示;
  :数字B状態に遷移;
elseif (四則演算押下) then (yes)
  :Ope = 押下された四則演算;
else (イコール押下)
  :b = a;
  :displayNum = a ope bの計算を実行;
  :displayNumを表示;
  :a = Integer.parseInt(displayNum);
  :計算結果状態に遷移;
endif
stop
@enduml